export default [
    // Ngôn ngữ hiểu
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Cô tạo âm thanh khác trong phòngkhi trẻ chưa có hoạt đông nào. ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Cô tạo ra âm thanh để trẻ thể hiện sự nhận thức về âm thanh bằng cách quay mắt và đầu. ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Thể hiện sự nhận thức về âm thanh bằng cách trở nên năng động hơn,  quay mắt và đầu, và nhìn vào người đối diện. ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Thể hiện sự nhận thức về giọng nói bằng cách quay mắt và đầu nhìn vào người đối diện ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Thể hiện sự nhận thức bằng cách giơ tay hoặc bò/đi về phía người chăm sóc  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Thể hiện sự nhận thức thông qua cử động cơ thể, âm thanh hoặc biểu cảm khuôn mặt dự đoán trong các hoạt động tương tác cảm giác xã hội  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Hướng mắt và đầu về phía người thân/yêu mến  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Phản ứng với điểm gần bằng cách quay đầu về hướng vật thể hoặc vị trí đó  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ nhìn vào tranh trong sách sau khi người lớn nói từ và chỉ vào tranh trong sách  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Nhìn vào vật thể khi người lớn ra hiệu (có hoặc không kèm lời nói).  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Nhìn vào vật thể khi người lớn ra hiệu (có hoặc không kèm lời nói).  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Quay đầu và nhìn về hướng một điểm ở vị t rí xa ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ đáp lại cử chỉ hoặc lời nói của người lớn bằng cách đặt hoặc cố gắng đặt đồ vật trong tay xuống.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Sử dụng các biểu tượng khác nhau thông qua lời nói hoặc giao tiếp phi ngôn ngữ cho năm đối tượng khác nhau ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Ngừng hành động khi người lớn sử dụng lời nói  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'nói/cử chỉ mang tính chất ngăn cản (lời nói, ngôn ngữ ký hiệu, cử chỉ, v.v.; "Không," "Dừng lại," "Chờ đã") bằng cách tạm thời ngừng hành động  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ em thường nhìn về phía hoặc di chuyển về phía (ví dụ: bò, đi bộ) một người lớn rất quen thuộc khi người lớn giao tiếp bằng lời nói, ngôn ngữ ký hiệu, cử chỉ hoặc hình thức giao tiếp khác. ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Thực hiện hành động theo hiệu lệnh bằng lời nói/cử chỉ. Đạt yêu cầu là khi trẻ thực hiện ít nhất năm hành động ngay lần đầu tiên. Ví dụ như người lớn lặp lại hướng dẫn, sử dụng cử chỉ để nhấn mạnh hành động (ví dụ: vỗ vào ghế để trẻ ngồi xuống, giơ xô lên để trẻ dọn dẹp), hoặc hướng dẫn trẻ một phần thực hiện hành động Đáp lại lời nói, ngôn ngữ ký hiệu, cử chỉ hoặc hình thức giao tiếp khác của người lớn, trẻ thực hiện năm hành động cơ thể quen thuộc (ví dụ: ngồi xuống, đưa đồ vật, cất đồ vật).  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Đáp lại lời nói, ngôn ngữ ký hiệu, cử chỉ hoặc hình thức giao tiếp khác của người lớn, trẻ thực hiện năm hành động cơ thể quen thuộc (ví dụ: ngồi xuống, đưa đồ vật, cất đồ vật).  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Đáp lại lời nói, ngôn ngữ ký hiệu, cử chỉ hoặc hình thức giao tiếp khác của người lớn, trẻ thực hiện ba hành động cơ thể (ví dụ: lắc đồ chơi, ném bóng, nhảy, vỗ tay).  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Thực hiện hành động theo hiệu lệnh bằng lời nói/cử chỉ. Một lần đạt yêu cầu là khi trẻ thực hiện ít nhất năm hành động ngay lần đầu tiên. Ví dụ như người lớn lặp lại hướng dẫn, sử dụng cử chỉ để nhấn mạnh hành động (ví dụ: vỗ vào ghế để trẻ ngồi xuống, giơ xô lên để trẻ dọn dẹp), hoặc hướng dẫn trẻ một phần thực hiện hành động ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Hoàn thành hướng dẫn bằng cách thực hiện hành động mà không cần cử chỉ hoặc sự hướng dẫn trực tiếp từ người lớn. Người lớn có thể lặp lại hướng dẫn lần thứ hai mà không cần tín hiệu bằng cử chỉ  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Hoàn thành ít nhất năm chỉ dẫn khác nhau bằng cách thực hiện hành động khi chỉ dẫn bao gồm cả lời nói và cử chỉ  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Thực hiện các hành động có hoặc không có đối tượng khi người lớn ra lệnh bằng động từ, với bốn đến năm động từ ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ chỉ phản ứng với hướng dẫn bằng lời nói; dừng hoàn toàn hoạt động, nhìn người lớn và chờ hướng dẫn từ người lớn.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ phản ứng với các chỉ dẫn bằng lời nói liên quan đến động từ (ví dụ: lắc nhạc cụ maraca, gõ gậy, ôm em bé, chọc bột, cắt, đứng dậy, vỗ tay, vẫy tai; phải thực hiện cả hai loại hành động - hành động của cơ thể và hành động trên đồ vật) ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Đạt yêu cầu khi nhận diện được 5 bộ phận cơ thể hoặc nhiều hơn  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ có phản ứng lại với “gì đây?” “con có….” “cho cô xem…..” 8 – 10 đồ vật cụ thể nào đó trong khi chơi, khi mặc quần áo, khi ăn trong tương tác với người lớn  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Phản ứng lại với “… ở đâu?” hoặc “Chỉ cho tôi … ?” bằng việc chỉ bằng ngón trỏ và nhìn  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Đạt yêu cầu khi trẻ thể hiện được hiểu biết chung về 3 giới từ hoặc hơn bằng cách làm theo những chỉ dẫn bằng lời trong đó có sử dụng đồ vật ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Đạt yêu cầu khi phản ứng lại với 4 tên gọi khác nhau hoặc hơn. Nếu người/ vật nuôi có mặt ở đó, trẻ phải nhìn vào người hoặc vật nuôi đó khi tên được gọi (cũng có thể chỉ). Nếu là tranh ảnh, trẻ chạm hoặc chỉ vào bức tranh khi được gọi tên. ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Khi phản ứng với yêu cầu bằng lời “Lấy …”, trẻ lấy đồ vật trong phòng nhưng ngoài tầm nhìn. Nhiệm vụ bao gồm nhớ được yêu cầu đủ lâu để thực hiện việc tìm kiếm bằng mắt ở trong phòng, và lấy được đồ vật trên sàn, trên bàn, ghế hoặc trên giá.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ xâu chuỗi 2 hành động với nhau trên một đồ vật đáp lại một hướng dẫn bằng lời kèm cử chỉ điệu bộ. Cần phải thể hiện được 3 chuỗi hành động khác nhau hoặc nhiều hơn mới đạt yêu cầu (VD: “Đi tìm và đem giầy của con lại cho cô”). ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Nhận diện được 5 bộ phận cơ thể hoặc nhiều hơn trong một bức ảnh lớn hoặc bản vẽ khi được hỏi.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Ở cùng với người lớn, rất tập trung chú ý và tham gia vào câu chuyện mà người lớn đang đọc. Các VD như giao tiếp mắt giữa các trang sách và người lớn, chỉ vào tranh ảnh trong sách, lật các trang sách, nói tên các bức tranh trong sách.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Thực hiện chỉ dẫn bằng cách nhìn vào người lớn và thực hiện hành động mà không cần người lớn phải dùng cử chỉ điệu bộ hoặc hành động để hướng dẫn. Người lớn có thể nhắc lại chỉ dẫn một lần nữa mà không cần ra tín hiệu cử chỉ điệu bộ. ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Vượt qua nếu nhận ra được 50 đồ vật phổ biến hoặc nhiều hơn.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Nói “có/ không” phù hợp với ngữ cảnh yêu cầu hoặc từ chối. Cần có cả giao tiếp mắt, mặc dù không cần đi kèm cử chỉ điệu bộ (VD: gật/ lắc đầu). Có thể sử dụng các cụm như “có/vâng”, “không, cảm ơn”.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Phát âm và/ hoặc ra cử chỉ điệu bộ (VD: chỉ tay) đáp lại câu hỏi của người lớn. Các VD: “Chỉ cho cô em bé đang ngủ?” hoặc “Con có nhìn thấy con chó đang chạy không?” Phản ứng không cần đi kèm với giao tiếp mắt  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Đều đặn làm theo các chỉ dẫn từ 2 – 3 phần gồm các hành động và đồ vật theo thói quen đã được làm hàng ngày  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Các VD là sử dụng các khái niệm một cách phù hợp khi được đề nghị (“Đặt quả bóng ở cạnh xe ô tô” hoặc “Đặt quả bóng ở dưới gầm bàn”) Phát âm hoặc dùng cử chỉ điệu bộ (VD: chỉ tay, cầm đồ vật) để phản ứng lại với câu hỏi của người lớn. Các VD: “Quả bóng to đâu?” hoặc “Chỉ cho cô chiếc ô tô nhỏ”. Phản ứng lại không cần đi kèm giao tiếp mắt.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Phát âm và/ hoặc ra cử chỉ điệu bộ (VD: chỉ tay) đáp lại câu hỏi của người lớn. Các VD: “Chỉ cho cô em bé đang ngủ?” hoặc “Con có nhìn thấy con chó đang chạy không?” Phản ứng không cần đi kèm với giao tiếp mắt  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Phát âm hoặc ra cử chỉ điệu bộ (VD: chỉ tay, cầm đồ vật) để phản ứng lại với câu hỏi của người lớn. Các VD: “Con gì kêu ‘meo meo’?”, “Con chó kêu thế nào nhỉ?” hoặc “Con nghe thấy gì?”. Phản ứng lại không cần đi kèm giao tiếp mắt. ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Phát âm hoặc ra cử chỉ điệu bộ (VD: chỉ tay, cầm đồ vật) để phản ứng lại với câu hỏi của người lớn. Các VD: “Chúng ta lái bằng gì?” hoặc “Chúng ta dùng gì để uống?”. Phản ứng lại không cần đi kèm giao tiếp mắt. Vượt qua khi xác định được tối thiểu 3 chức năng của đồ vật  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Phát âm hoặc ra cử chỉ điệu bộ (VD: chỉ tay, cầm đồ vật) để phản ứng lại với câu hỏi của người lớn. Người lớn có thể sử dụng một đồ vật thuộc sở hữu của trẻ để thăm dò khả năng hiểu. Các VD: “Lượt này của ai?” hoặc “Chiếc giầy này của ai?” Phản ứng lại không cần đi kèm giao tiếp mắt. ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Phát âm hoặc ra cử chỉ điệu bộ (VD: chỉ tay, cầm tranh, thể hiện hành động) để phản ứng lại với câu hỏi của người lớn. Các VD: “Chỉ cho cô cách con ném bóng” hoặc “Cho cô xem con lợn đang ăn”. ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Hoàn thành chỉ dẫn bằng cách nhìn vào người lớn và thực hiện hành động mà không cần chỉ dẫn bằng cử chỉ điệu bộ hoặc hành động của người lớn. Người lớn có thể nhắc lại chỉ dẫn một lần nữa mà không cần dùng tín hiệu cử chỉ điệu bộ. Các VD: “Đưa cho cô chiếc xe ô tô và đóng sách lại” hoặc “Đặt quả bóng vào xô, và đặt búp bê lên bàn”.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Cầm lên, đưa cho, chỉ tay hoặc chọn 1 trong 2 đồ vật đúng cho người lớn. Trẻ xác định được đúng 5 khái niệm khác nhau. Các VD: nóng/ lạnh, hết/ đầy, ướt/ khô, cứng/ mềm, nặng/ nhẹ, cao/ thấp, dài/ ngắn, lớn/ bé.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Cầm lên, đưa, chỉ hoặc cho người lớn xem đồ vật đúng (VD: Người lớn hỏi “Cô có thể lấy chiếc bút màu xanh không?” và trẻ đưa đúng đồ  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ cầm lên, đưa, chỉ hoặc cho xem nhân vật nam hoặc nữ, hình tượng hoặc người thực phản ứng lại một cách phù hợp với những chỉ dẫn gồm “trai hay gái”. VD: “Đặt cậu bé vào ô tô” hoặc “Chị ấy muốn một vài cây kem”. Trẻ cần vượt qua ít nhất 1 đại từ về giới tính.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Cầm lên, đưa, chỉ tay hoặc cho xem đồ vật đúng cho người lớn trong một nhóm có 4 – 5 vật để lựa chọn. Để vượt qua, trẻ cần phải hiểu được 3 nhóm so sánh hoặc nhiều hơn.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ hiểu được những khái niệm: bên cạnh, đằng sau, ở trước bằng cách để đồ vật đúng vị trí hoặc nhìn vào địa điểm đúng khi được hướng dẫn (VD: “Nhìn đằng sau ghế”).  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Cầm lên, đưa, chỉ tay hoặc cho xem các đồ vật đúng để xác định đúng sự thiếu vắng một đồ vật nào đó (chiếc bát không có quả sơ ri) hoặc đặc điểm (đứa trẻ không có mắt màu xanh) hoặc một hành động bị thiếu (người đang không ngủ).  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Với đồ vật và tranh ảnh, trẻ chỉ tay hoặc cho xem bộ phận nào đó khi được yêu cầu (VD: mũi con thỏ, bánh xe, cánh cửa xe ô tô).  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ lắng nghe những câu chuyện đơn giản khi người lớn đọc (5 trang). Trẻ thể hiện sự quan tâm chú ý bằng cách cùng người lớn nhìn vào cuốn sách và phản ứng lại một cách chính xác câu hỏi ai/ cái gì bằng lời hoặc bằng chỉ tay. Trả lời được 2 – 3 câu hỏi  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trả lời đúng bằng cách phát âm hoặc gật/ lắc đầu khi người lớn hỏi “Có phải là …?” hoặc “Tên con là Sam phải không?”  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ phản ứng đúng với cụm câu hỏi “Con sẽ làm gì nếu …?” cho 4 trạng thái hoặc nhiều hơn: đau, mệt, đói, khát.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Phản ứng đúng với 3 câu hỏi liên quan đến thông tin cá nhân hoặc nhiều hơn. Các VD: “Tên con là gì?” (Họ và tên), “Số điện thoại của con là bao nhiêu?”, và “Địa chỉ của con là gì?”. ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Cầm lên, đưa, chỉ tay và cho xem các đồ vật/ tranh ảnh đáp lại những hướng dẫn như tìm đồ vật giống nhau, và các đồ vật/ tranh ảnh khác nhau.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Cầm lên, đưa, chỉ tay hoặc cho xem đồ vật hoặc tranh ảnh phản ứng lại với các từ chỉ số lượng: một, một vài, tất cả, một ít, hầu hết. Cần phải vượt qua được hết mới đạt.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Cầm lên, đưa, chỉ tay hoặc cho xem đồ vật với đặc điểm như người lớn thể hiện. VD: người lớn nói “Đưa cho cô con chó có tai dài” và trẻ chỉ đúng. Các đặc điểm bao gồm kích cỡ, hình dáng, chất liệu, trạng thái thể chất (lỏng/rắn, mềm/cứng, nhũn/dai…)  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Vượt qua nếu hiểu được 10 – 15 đặc điểm.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ hiểu các đặc điểm đồ vật bao gồm: màu sắc, hình dạng, kích cỡ hoặc chức năng; cái màu xanh, cái tròn, cái to, cái trẻ dùng để ăn.  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ xác định được thì quá khứ, những gì đã xảy ra (VD: “Chỉ cho cô cậu bé đã nhảy?”. Tương tự với  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'thì tương lai. Cần phản ứng lại chính xác ở cả hai thì  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ hiểu được thể bị động thông qua hành động với đồ vật hoặc sự lựa chọn tranh ảnh (VD: “Con chó bị quả bóng đập vào”, “Cô bé bị cậu bé đuổi”).  ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Trẻ phản ứng lại chính xác với 3 hướng dẫn có liên hệ thời gian: đầu tiên/ cuối cùng, trước/ sau, cùng lúc ' },
    {fieldId: 'VwWwTwTaRGrvnjIgFq1y', name: 'Tuân theo yêu cầu của người lớn gồm 3 phần. VD: người lớn nói “Đưa cho cô cái cốc”, “Hôn con gấu”, và “Đóng hộp”. Vượt qua nếu thể hiện đúng.  ' },

    // Ngôn ngữ diễn đạt

    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát ra các âm nguyên âm, chẳng hạn như "ah," "oo," "ee," khi người lớn sử dụng các âm thanh trong lúc chơi đùa  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát ra các âm nguyên âm, chẳng hạn như "ah," "oo," "ee," với ngữ điệu khác nhau khi người lớn sử dụng âm thanh trong lúc chơi đùa hoặc khi ở một mình  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trong các hoạt động xã hội, chúng phát ra những âm thanh thể hiện sự thích thú (ví dụ: tiếng ríu rít, tiếng kêu vui sướng) và cũng phát ra những âm thanh thể hiện sự không hài lòng (ví dụ: tiếng càu nhàu, tiếng rên rỉ).  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Thỉnh thoảng, trẻ phát ra hai đến ba âm phụ âm khác nhau (ví dụ: "b-b," "m-m²") khi người lớn sử dụng âm thanh trong lúc chơi đùa.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Tạo ra một vài tổ hợp khác nhau của các âm CV đơn lẻ (ví dụ: "ba," "moo," "go")  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ phát ra tiếng la hét, tiếng cười, tiếng thổi kèn và các âm thanh không phải lời nói khác khi người lớn sử dụng giọng nói trong lúc chơi đùa ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Lặp lại các âm tiết CV bằng cách sử dụng cùng một âm ("ba, ba, ba") hoặc các âm khác nhau ("ba, da, ba, da") khi người lớn đang sử dụng các âm thanh trong khi chơi.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Kết hợp các âm tiết khác nhau khi phát âm, chẳng hạn như "papadaba" hoặc "mamalata," khi người lớn sử dụng các âm thanh này trong lúc chơi đùa Trẻ tự nhiên sử dụng các phụ âm m, b và p (ví dụ: "pa," "ba," "ma") khi người lớn đang phát âm trong lúc chơi đùa.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ tự nhiên sử dụng các phụ âm m, b và p (ví dụ: "pa," "ba," "ma") khi người lớn đang phát âm trong lúc chơi đùa.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ sử dụng các phụ âm t, d, n, h và y (ví dụ: "ta," "da," "no," "hep," "ya") khi người lớn phát âm trong lúc chơi đùa.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ sử dụng các phụ âm t, d, n, h và y (ví dụ: "ta," "da," "no," "hep," "ya") khi người lớn phát âm trong lúc chơi đùa.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Ghép nối nhiều âm tiết với nhau bằng một mô hình giống như lời nói, thay đổi về cao độ, âm điệu hoặc trọng âm  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Yêu cầu một vật thể hoặc một hành động bằng cách sử dụng các cử động cơ thể, chẳng hạn như với tay, duỗi chân hoặc đưa tay ra  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Hành động với tay về phía vật mong muốn trong tay người lớn để thể hiện yêu cầu. Cử chỉ này không cần kèm theo giao tiếp bằng mắt hoặc lời nói. Không bao gồm việc với tay chỉ để giật lấy ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Khi được lựa chọn giữa một vật ưa thích và một vật không ưa thích, người đó sẽ với tay lấy hoặc nhìn vào vật ưa thích ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát ra âm thanh kết hợp với giao tiếp bằng mắt và/hoặc cử chỉ (ví dụ: với tay) để yêu cầu món đồ hoặc vật dụng mong muốn  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Hành động này thể hiện sự cần giúp đỡ bằng cách đặt đồ vật vào tay người lớn, đưa đồ vật cho người lớn, nói chuyện hoặc nhìn về phía người lớn. Cử chỉ không nhất thiết phải đi kèm với giao tiếp bằng mắt hoặc lời nói/phát âm  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Yêu cầu một vật thể, hành động hoặc phản đối bằng cách sử dụng ít nhất hai hành động giao tiếp khác nhau, chẳng hạn như ra hiệu, với tay, ký hiệu hoặc nhìn vào người lớn  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ bập bẹ và/hoặc phát ra âm thanh kèm theo giao tiếp bằng mắt ít nhất hai lần  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Sử dụng các âm nguyên âm, chẳng hạn như "ah" và "oh," trong trò chơi luyện giọng tương tác với một người lớn trong ít nhất hai lượt  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Sử dụng các âm CV, chẳng hạn như "ba" và "da," trong trò chơi luyện giọng đối đáp với một người lớn trong ít nhất hai lượt  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Cử chỉ không nhất thiết phải đi kèm với giao tiếp bằng mắt hoặc lời nói/phát âm. Hãy ghi nhận những cử chỉ thông thường khác (lắc đầu, ra hiệu "xong rồi") hoặc lời nói ("không").  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ dùng ngón trỏ hoặc ngón giữa (không dùng bàn tay mở) chạm hoặc chỉ vào vật thể trong phạm vi 15-30 cm để thể hiện yêu cầu. Vật thể đó có thể nằm trong tay người lớn hoặc trong tầm với của trẻ  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ quay đầu và nhìn người lớn, duy trì giao tiếp bằng mắt trong 1-2 giây, có hoặc không kèm theo cử chỉ (ví dụ: với tay, nắm lấy) để yêu cầu đồ vật.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Khi yêu cầu một vật hoặc yêu cầu giúp đỡ bằng bất kỳ hình thức giao tiếp nào (lời nói, cử chỉ, ký hiệu, v.v.), trẻ sẽ nhìn qua lại giữa vật cần yêu cầu và người được yêu cầu  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Người lớn giơ hai vật, mỗi tay cầm một vật. Chạm hoặc chỉ vào vật mong muốn bằng ngón trỏ hoặc ngón giữa (không dùng bàn tay mở). Cử chỉ không cần kèm theo giao tiếp bằng mắt hoặc lời nói  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ quay đầu và nhìn người lớn, giao tiếp bằng mắt và phát ra âm thanh để yêu cầu vật thể mong muốn. Âm thanh phát ra có thể chỉ là gần đúng. Ví dụ như "aah" khi muốn gọi bóng và "ooh" khi muốn gọi "đi". ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Chỉ vào một vật thể, hình ảnh hoặc người nhằm mục đích thu hút sự chú ý của người khác đến vật thể, hình ảnh hoặc người đó, hoặc nhằm mục đích gọi tên chúng  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Người lớn giơ hai vật lên, mỗi tay cầm một vật nhưng để ngoài tầm với của trẻ, rồi chỉ cho trẻ xem và gọi tên từng vật. Trẻ dùng ngón trỏ (không dùng bàn tay mở) chỉ vào vật mà trẻ muốn trẻ muốn nhưng nằm ngoài tầm với. Hành động này không cần kèm theo giao tiếp bằng mắt hoặc lời nói  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Chỉ vào một vật thể, hình ảnh hoặc người nhằm mục đích thu hút sự chú ý của người khác đến vật thể, hình ảnh hoặc người đó, hoặc nhằm mục đích gọi tên chúng  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Tự nhiên nhìn qua lại giữa một vật thể và một người lớn với mục đích thu hút sự chú ý của người kia vào vật thể đó  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Việc phát âm diễn ra có hoặc không có sự hướng dẫn bằng lời nói của người lớn. Trò chơi phát âm cũng được tính  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ kết hợp cử chỉ điệu bộ đặc biệt và giọng nói hoặc phát âm từ gần đúng (nói không chuẩn) để giao tiếp tất cả các chức năng này.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm từ trong sinh hoạt hàng ngày, thói quen xã hội quen thuộc. Có thể tự phát  hoặc  bắt chước lại nhưng người lớn không được nhắc trẻ ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm 3 từ tương đương khác nhau hoặc nhiều hơn gồm các động từ liên quan đến các hành động cơ thể hoặc tương tác với đồ vật – tự phát hoặc bắt chước nhưng không được nhắc ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ tự phát sử dụng từ, dù có thể chưa đúng hoàn toàn, để yêu cầu hoạt động hay đồ vật. Phải dùng được cả danh từ và các loại từ khác mới đạt yêu cầu  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Đạt yêu cầu nếu trẻ nói được tên của 5 đồ vật hoặc nhiều hơn và 5 bức tranh hoặc nhiều hơn một cách tự phát ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ có các ngữ điệu khác nhau khi phát âm một số từ trong bài hát hoặc ngâm nga, thể hiện nhận thức về ngữ điệu trong đó  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ sử dụng các từ đơn với ánh nhìn để truyền tải cả yêu cầu và phản đối, từ chối hoặc phủ nhận ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ phát âm tối thiểu 10 động từ, cả bắt chước lẫn tự phát để gắn tên cho những hành động của bản thân, của người khác hay đối với đồ vật ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ sử dụng tên để gọi người trong bức tranh, trong gương và ngoài đời thực hoặc để thu hút sự chú ý của người đó. Có thể trong phản ứng lại với câu hỏi “Ai đó?”  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ kết hợp một cách tự phát việc lắc đầu kèm nói “không” để từ chối một lời đề nghị.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ kết hợp một cách tự phát việc gật đầu kèm nói “có” để chấp nhận một đề nghị ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ nhìn vào người lớn một cách tự phát và cử chỉ điệu bộ hướng về đồ vật trong khi hỏi “Cái gì đây?” trong vài ngữ cảnh khác nhau  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ thể hiện sự chú ý hướng vào đồ vật được đưa ra ở khoảng cách gần  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ thể hiện sự chú ý hướng vào đồ vật/người được chỉ cho thấy ở khoảng cách xa  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Việc này gồm đưa và nhận. Nếu là nhận, người lớn không nên đưa ngay đồ vật ra. Ánh nhìn thể hiện sự giao tiếp “yêu cầu”  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phản ứng với “cho … xem nào!”, trẻ chìa đồ vật về phía người lớn  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ biết đưa đồ chơi ra trước mặt người lớn, nhìn vào người lớn và chờ đợi một lời nhận xét. Nếu trẻ tự thể hiện hành vi này vài lần trong 1 giờ chơi là đạt yêu cầu  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Người lớn thu hút được ánh nhìn của trẻ trong tương tác mặt đối mặt và sau đó quay ra nhìn đồ vật. Vượt qua nếu trẻ có quay đầu và tìm kiếm một chút. Không cần phải tìm được đích.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ tự thể hiện hành vi này vài lần trong mỗi giờ. Trẻ cần phải chỉ được đích và nhìn vào người lớn rồi chờ đợi lời bình luận thì mới đạt yêu cầu.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ đưa ánh mắt nhìn từ đồ vật sang mắt người lớn và quay trở lại đồ vật để chia sẻ niềm vui. Cần phải thấy vài lần trong thời gian 10 phút của trò chơi xã hội để đạt yêu cầu  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm cần kèm cả giao tiếp mắt. Các VD: “Muốn thêm nước hoa quả”, “Tạm biệt Sally”, “Giúp con mở” hoặc “Không bóng”. Phát âm không cần hoàn hảo.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm cần kèm cả giao tiếp mắt và không liên quan đến việc đồ vật hoặc hành động để yêu cầu. Các VD: “Xem con bò”, “Máy bay bay nhanh” hoặc “Con chó con”. Phát âm không cần hoàn hảo. ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm không cần đi kèm giao tiếp mắt. Các VD: “Em bé ăn” hoặc “Con chim bay”. Phát âm không cần hoàn hảo.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm cần đi kèm cả giao tiếp mắt. Các VD: “Con thỏ trên bàn” hoặc “Quả bóng ở đó”. Phát âm không cần hoàn hảo.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm cần đi kèm giao tiếp mắt. Người lớn có thể sử dụng một đồ vật thuộc sở hữu của trẻ. Các VD: “Cái đó (cốc) của con”, “Lượt cô”, hoặc “Em bé của con”. Phát âm không cần hoàn hảo. ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm hoặc dùng cử chỉ điệu bộ (VD: nhún vai, giơ hai tay lên) cần bao gồm cả giao tiếp mắt. ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm cần đi kèm giao tiếp mắt. Người có thể muốn sử dụng gương để thăm dò. Phản ứng có thể gồm các  biến thể xưng hô của trẻ và đối tác.  Các VD : “Đó là con ” hoặc“Con thấy mẹ /cô…” ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm cần đi kèm giao tiếp mắt. Các VD: “Đi tới nói với mẹ “con chào mẹ”, hoặc “Đi gọi bố lại đây”. Phát âm không cần hoàn hảo. ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm và/ hoặc cử chỉ điệu bộ (VD: làm hành động) cần đi kèm giao tiếp mắt. Trẻ có thể sử dụng các từ đơn hoặc các cụm đơn giản. Các VD: “Con chó con”, “Bắt bóng” hoặc “Bóng bay lên”. Phát âm không cần hoàn hảo.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm và/ hoặc cử chỉ điệu bộ (VD: làm hành động) cần đi kèm giao tiếp mắt. Trẻ có thể sử dụng các từ đơn hoặc các cụm đơn giản. Các VD: “Con chó con”, “Bắt bóng” hoặc “Bóng bay lên”. Phát âm không cần hoàn hảo.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm không cần đi kèm giao tiếp mắt. Người lớn có thể hỏi “Xe ô tô màu gì?” nhưng trẻ cần tự trả lời (“ô tô đỏ”; “đó là quả bóng màu xanh”). Từ tương đương cũng chấp nhận được.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm không cần đi kèm giao tiếp mắt. Người lớn có thể hỏi lại lần nữa ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm cần kèm giao tiếp mắt. Câu hỏi có thể là câu có 1 từ với ngữ điệu tăng. Các VD: “Bánh?” hoặc “Đi?”  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm cần đi kèm giao tiếp mắt. Cần hỏi được cả 2 loại câu hỏi thì vượt qua ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm không cần đi kèm giao tiếp mắt. Các VD: “Tên con là gì?”, “Con bao nhiêu tuổi?”, hoặc “Áo con màu gì?”.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ trả lời đúng các câu hỏi liên quan đến các khái niệm này (VD: “Tại sao chúng ta rửa tay?” “Con đánh răng như thế nào?”.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Có thể mô tả chức năng của 5 đồ vật thông thường hoặc nhiều hơn bằng cách sử dụng các cụm đơn giản.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Hiểu để diễn đạt phù hợp đúng một số ngữ cảnh, các đối tác và các hoạt động.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ kết hợp được một số từ và tạo các cụm danh từ có thể dài 4 từ, gồm các mạo từ, đại từ sở hữu, tính từ và số từ (VD: “Chú ngựa nhỏ”, “Bút chì màu đỏ của con”, “Chiếc xe tải này”, “Hai cái bánh quy”, “Hình vuông to màu đỏ”).  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ nói các giới từ như danh sách ở bên để mô tả sự vật, trả lời câu hỏi và hướng dẫn người khác cách phân bố/sắp xếp.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Tự giải thích. (VD: cậu bé khóc, cô ấy thích cậu ấy, cậu ấy ngã, cậu ấy đã vui vẻ, cậu ấy đang vui) ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ thể hiện chính xác được 80% âm thanh trong hội thoại; tính dễ hiểu của lời nói với mỗi địa phương ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Khi được hỏi, trẻ miêu tả trải nghiệm gần đây với tối thiểu là 2 thành phần (ai, cái gì, ở đâu, khi nào). VD: “Con đã làm gì vào tiệc sinh nhật mình?”, “Con nhận được quà từ David”.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ xin phép trước khi điều chỉnh cái gì đó: “Con có thể khuấy lên không?” (chảo trên bếp) “Con có thể làm cái này không?” (sử dụng một dụng cụ của người lớn). Cũng có thể khi trẻ muốn bắt đầu một hoạt động khác“Chúng ta có thể nghe nhạc không?”  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ sử dụng từ chỉ số nhiều một cách nhất quán và tự phát (vd: vài, các, những, mấy…)  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ sử dụng đều đặn những từ này  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ sử dụng đều đặn mẫu thì quá khứ một cách tự phát và thường xuyên (vừa/đã + động từ)  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ sử dụng những danh từ chỉ đơn vị tự nhiên thường xuyên trong các câu và cụm từ, vd: cái, con, quyển, chiếc, cục, mẩu, miếng…  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Sư dụng 5 từ đúng hoặc nhiều hơn: tốt hơn, tốt nhất, to hơn, to nhất, bé hơn, bé nhất, béo hơn, béo nhất  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'VD: “Con không khóc”, “Con không đánh bạn ấy”, “Con sẽ không ngồi xuống”  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Phát âm cụm từ bao gồm kết hợp từ “đang” + “động từ”vd: Cậu bé đang lái xe.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ sử dụng 5 từ hoặc nhiều hơn để miêu tả trạng thái của bản thân: “Con đói, lạnh, khát, mệt, đau”. Trẻ phản ứng đúng với 5 trạng thái hoặc nhiều hơn  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ phản ứng đúng với 5 trạng thái hoặc nhiều hơn  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Đề cập một mục hoặc một nhóm mục nào đó theo tên hạng mục, theo 3 cấp độ: tên – nhóm – lớp/loại/loài VD con cá là động vật sống dưới nước.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ có thể gọi tên 3 đặc điểm hoặc nhiều hơn của 5 đồ vật thông thường khi được hỏi “Kể cho cô về ….”.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Sử dụng 2 đại từ phản thân hoặc nhiều hơn gồm: tự tôi, tự bạn, tự anh ấy, tư cô ấy, tự nó, tự ai đó, tự chúng tôi, tự chúng nó, tự họ.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Di chuyển tới chỗ điện thoại đang kêu, cầm lên và đặt vào tai, nói lời chào và nhận ra người đang gọi  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ duy trì hội thoại bằng cách thêm cách yếu tố, hỏi câu hỏi, bình luận hoặc hỏi và duy trì chủ đề xuyên suốt 2 -3 lượt hội thoại.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ bắt đầu hội thoại với một người khác bằng một bình luận hoặc câu hỏi và duy trì chủ đề xuyên suốt tối thiểu 4 lượt hội thoại ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trong phản ứng lại với một câu hỏi mở - kết (VD: “Kể cho cô về chuyến thăm bà ngoại”, trẻ sẽ miêu tả ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Khi được hỏi câu hỏi mà trẻ không biết câu trả lời, trẻ phản ứng lại một cách phù hợp.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ nói “Cái gì?” hoặc phản ứng tương tự khi trẻ không nghe thấy hoặc hiểu câu bình luận, câu hỏi hoặc hướng dẫn dành cho trẻ  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Tự sửa lời nói của mình nếu người nghe không hiểu  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ thể hiện các kỹ năng sửa lỗi (VD: lặp lại, nói lại cụm từ, kết hợp phát âm với cử chỉ điệu bộ, nhấn mạnh) để làm rõ ý khi đối tác không hiểu. ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trẻ có thể trả lời một số câu hỏi đơn giản khác nhau về bản thân và cũng có thể trả lời các câu hỏi về những người thân thuộc khác – các thành viên trong gia đình, thú cưng, bạn thân …  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Nói hoặc dùng cử chỉ điệu bộ với bạn cùng lứa (“lại đây chơi tàu hỏa đi”, “Hãy chơi đuổi bắt” hoặc vẫy tay với bạn).  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Sử dụng một số mẫu lịch sự như “không, cảm ơn”, “Cảm ơn”, “Rất hân hạnh”, “Xin lỗi” và “Rất tiếc”. ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Khi trẻ sợ, đau, hoặc thất vọng, trẻ lại gần người lớn hoặc tiếp xúc thể chất với người lớn (ôm, ngồi vào lòng, cầm tay)  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Nói cảm xúc của bản thân “Tôi đang bực” …  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Lần lượt với người lớn/ bạn cùng lứa khi tham gia chơi mà không cần phải xác định lượt rõ ràng.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Kể lại một câu chuyện bằng lời nói cho một người bạn gồm tối thiểu là 3 chi tiết.  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Nói 1 hoặc nhiều VD cho mỗi khái niệm (VD: vui, buồn, điên, sợ). VD: Người lớn nói “Tại sao con buồn?” và trẻ nói “Cô ấy lấy sách của con và con buồn”  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Trong các hoạt động đọc hoặc hội thoại, trẻ trả lời đúng khi được hỏi “Tại sao cô ấy khóc?” hoặc “Tại sao cậu bé sợ?”  ' },
    {fieldId: '0RptPhhmbwDhyXFstiet', name: 'Tham gia vào 1 hoặc nhiều cách cách giải quyết: VD: yêu cầu được nghỉ giải lao, yêu cầu trợ giúp, tới ôm, lấy một đồ vật yêu thích.  ' },

    // Kỹ năng xã hội

    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Phản ứng khác nhau đối với người quen và người lạ, thể hiện qua biểu cảm khuôn mặt hoặc hành động  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Khi nhìn thấy mình trong gương, trẻ mỉm cười, có những cử chỉ cơ thể hoặc vẻ e lệ, cho thấy trẻ  nhận ra chính mình trong gương  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ không có biểu hiện né tránh, thu mình hay cảm xúc tiêu cực  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Khi tham gia vào hoạt động yêu thích cùng người lớn, trẻ sẽ mỉm cười hai đến ba lần  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Khi người khác thể hiện cảm xúc, chẳng hạn như niềm vui hoặc nỗi buồn, trẻ sẽ nhận thấy và phản  ứng bằng cách thể hiện cảm xúc tương tự, tiến lại gần người đó và/hoặc an ủi người đó (thấu cảm sơ khai – lây lan cảm xúc)  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Khi có người lạ tiếp cận, trẻ phản ứng bằng cách lùi lại và/hoặc tỏ ra sợ hãi hoặc rụt rè  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Ví dụ về các gợi ý vận động bao gồm với tay, bắt chước chuyển động của người lớn và đưa đồ vật cho người lớn. Gợi ý vận động không nhất thiết phải đi kèm với giao tiếp bằng mắt  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Biểu hiện bằng cách nhìn và duy trì giao tiếp bằng mắt với người khác trong 2 giây.  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Thể hiện sự quan tâm đến các hoạt động xã hội cảm giác bằng cách tiếp cận, quan sát hoặc chủ ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Phản hồi không nhất thiết phải kèm theo giao tiếp bằng mắt  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Thể hiện sự hứng thú với hoạt động bằng cách quan sát và bắt chước các hành động chơi của người lớn, đồng thời tiếp tục duy trì cách chơi đang được bắt chước đó  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Tham gia từ hai lần trở lên vào bất kỳ hành vi tích cực nào (với tay, bắt chước, phát âm) trong trò  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'chơi. Chỉ giao tiếp bằng mắt và mỉm cười thôi là chưa đủ. Ví dụ bao gồm trò úp mặt, các bài đồng dao/bài hát ("Nhện Nhỏ Xíu", "Nếu Bạn Vui Và Bạn Biết Điều Đó"), các trò chơi("Vòng Tròn Xung Quanh Hoa Hồng", "Vỗ Tay"), bong bóng, bóng bay, sách, máy bay, "Chuột Con Đến Rồi".  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ cười khi người lớn che rồi lại bỏ tay khỏi mắt trẻ  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ thể hiện sự nhận thức về lời chào bằng cách quay đầu và thân người, nhìn người lớn trong 2-3 giây ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Thể hiện sự nhận thức về việc chào hỏi bằng cách quay đầu và thân người, vẫy tay hoặc nói "Chào/Tạm biệt" kèm theo giao tiếp bằng mắt trong 2-3 giây  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trong lúc chơi đùa với người lớn, trẻ sẽ cười và giao tiếp bằng mắt trong 2-3 giây  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ bắt đầu trao đổi giao tiếp (bất kỳ dạng nào) với ánh nhìn và duy trì ánh nhìn đó theo một cách tự nhiên trong suốt quá trình trao đổi  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ khởi xướng và đưa ra tín hiệu ánh nhìn khi di chuyển cơ thể, cử chỉ điệu bộ hoặc giọng nói cụ thể trong một trò chơi nào đó. Để vượt qua cần phải yêu cầu được 3 trò chơi hoặc nhiều hơn ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ ôm những người lớn quen thuộc một cách tự phát, hôn vào má hoặc môi  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ tìm kiếm giao tiếp mắt từ người lớn bằng cách sử dụng từ hoặc cử chỉ điệu bộ rõ ràng (vẫy tay, chỉ, quay mặt, vỗ nhẹ …)  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ phản ứng lại với lời chào hỏi bằng cả các từ và cử chỉ điệu bộ không cần nhắc nhở ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ khởi xướng yêu cầu giúp đỡ bằng cách sử dụng các ký hiệu thông thường/ theo quy ước hoặc từ tương đương kết hợp với ánh nhìn. Không tính chuyển động của tay và cơ thể trừ phi đi kèm với cả ánh nhìn và các từ phù hợp ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ kết hợp nhất quán các hành động giao tiếp tự phát với ánh nhìn  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ chơi một số trò chơi vòng tròn khác nhau và bắt chước chuyển động nhảy theo nhạc (“Hokey Pokey”, “Chơi vòng quanh”, “Cầu Luân Đôn”) ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ đuổi theo một người khác và bắt được người đó trong trò chơi “đuổi bắt”, và cũng chạy khi bị người khác đuổi trong trò chơi đó  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ khởi xướng một cách tự phát các trò chơi xã hội quen thuộc với một đối tác bằng cách thiết lập giao tiếp mắt và sử dụng cử chỉ điệu bộ đi kèm tên hoặc một từ chỉ hành động (VD: “cù”,“đuổi”)  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ phản ứng lại một cách nhất quán với yêu cầu bằng lời bằng cách nhìn và đưa đồ vật cho người ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ tham gia hát một bài quen thuộc và các trò chơi xã hội với mô hình chuyển động phù hợp trong một nhóm nhỏ (1 – 2 trẻ khác) mà không cần sự giám sát đặc biệt nào đó  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ tiếp tục hoạt động khi bạn cùng lứa tham gia vào, hiểu và tiếp nhận sự tham gia của bạn cùng lứa. Trẻ không “giữ” đồ chơi cho riêng mình hay từ chối sự tiếp cận đó.  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ phản ứng lại một cách tự phát với “Chào” và “Tạm biệt” từ một người bạn cùng lứa bằng việc nhìn, có cử chỉ điệu bộ và từ phù hợp ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trong tình huống chơi song song, trẻ phản ứng lại một cách đều đặn với yêu cầu chơi lần lượt của bạn bằng cách đưa đồ vật khi được yêu cầu và yêu cầu chơi khi tới lượt của mình bằng ngôn ngữ hoặc cử chỉ, kết hợp cả với ánh nhìn  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ ngồi trong một nhóm nhỏ mà không cần một chỗ đặc biệt nào hoặc sự trợ giúp từ người lớn, tham gia chú ý tới người lớn và làm theo các chỉ dẫn bằng lời trong khả năng của trẻ. Người lớn có thể gọi tên trẻ để chuyển tải chỉ dẫn nhưng không nhắc thêm gì khác.  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ đều đặn nhận đồ vật kèm giao tiếp mắt khi một bạn cùng lứa đưa cho  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trẻ phản ứng lại một cách nhất quán phù hợp với các yêu cầu về đồ vật trong các tình huống ở nhóm nhỏ (VD: vòng tròn buổi sáng, bàn ăn bữa phụ, bàn vẽ/ nghệ thuật, góc diễn kịch).  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Trong các hoạt động chơi song song, trẻ sẽ bắt chước một vài hành động của bạn cùng lứa một cách tự phát ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Đạt yêu cầu nếu trẻ biết chơi theo lượt với bạn và hoàn thành trò chơi ghép tranh. Chỉ cần có các kỹ năng này là đã vượt qua mục này.  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Có tối thiểu 2 lần tham gia các hành động tích cực (chạm tới, bắt chước, phát âm) trong ít nhất 3 trò chơi. Chỉ giao tiếp mắt và cười là không đủ. Các VD: “Trốn tìm”, “Chơi vòng quanh”, chơi bóng ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Phản ứng lại trong vòng 3 giây với yêu cầu của đối tác. Đối tác có thể lặp lại lần thứ 2. Phản ứng có thể bao gồm phát âm (VD: “em bé”) hoặc cử chỉ điệu bộ (VD: mang đồ vật cho người lớn, cầm đồ vật trong tay).  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Có tối thiểu 2 lần tham gia các hành động tích cực trong 2 thói quen hoặc nhiều hơn. Chỉ giao tiếp mắt và cười là không đủ. Các VD: “Các ngón tay ngoắc ngoắc”, “Cù” “Nhện giăng tơ”  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Báo cáo của phụ huynh có thể được chấp nhận. Các VD: “Lấy bóng”, “… là mẹ (đóng vai) ”, hoặc “Đặt nó ở đây”.  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Báo cáo của phụ huynh có thể được chấp nhận. Khởi xướng/ bắt chước tối thiểu 2 vòng trong ít nhất 3 trò chơi phù hợp độ tuổi (VD: “đuổi bắt”, ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Báo cáo của phụ huynh có thể được chấp nhận. Tham gia tối thiểu 2 vòng. Các hành vi có thể gồm phát âm (VD: “Em bé đói”), bắt chước, hoặc quan sát đối tác chơi. Các VD trò chơi quen thuộc hàng ngày như chơi ngôi nhà, mặc quần áo, chơi đóng vai.  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Tham gia vào nhiều hơn 2 vòng trong ít nhất 3 trò chơi phù hợp với lứa tuổi. Các VD: “Nối 4 điểm”, “Săn tuần lộc” hoặc “Vịt may mắn”.  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Các VD: “Làm ơn”, “Cảm ơn” hoặc “Xin lỗi” một cách tự phát và phù hợp. Từ tương đương có thể chấp nhận được. Vượt qua nếu sử dụng thường xuyên được 2 trong 3 từ  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Các VD: “Làm theo người dẫn đầu”, “Simon nói” hoặc giả vờ di chuyển như các con vật. Tự phát bắt chước 10 hành động mới lạ hoặc hơn. Có thể không chính xác  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Tham gia vào 3 hoạt động hoặc nhiều hơn với các hành vi chủ động (nói, thực hiện hành động, bắt chước). Chỉ giao tiếp mắt và cười là không đủ. Các VD: chơi gia đình, đóng vai giáo viên hoặc cho em bé vào giường ngủ.  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Khởi xướng các hành vi tối thiểu 3 lần có giao tiếp mắt. Các VD lời nói (VD: “Mẹ, nhìn, mèo”, “Đổ khối gỗ”, hoặc “Bố, thêm bánh”) kèm cử chỉ điệu bộ (VD: đưa hoặc cầm đồ vật cho người lớn, chỉ vào mục).  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Phản ứng lại trong vòng 3 giây với sự mời gọi của người lớn. Người lớn có thể lặp lại thêm một lần nữa.  ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Phản ứng lại trong vòng 3 giây với khởi xướng của người lớn. Người lớn có thể lặp lại thêm một lần nữa. Xác định được 2 hoặc nhiều hơn loại cảm xúc đang tác động (VD: vui, buồn, ngô nghê, sợ, ngạc nhiên). Lời nói không cần đi kèm giao tiếp mắt ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Diễn tả được 2 hoặc nhiều hơn loại cảm xúc đang tác động (VD: vui, buồn, ngô nghê, sợ, ngạc nhiên). Lời nói không cần đi kèm giao tiếp mắt ' },
    {fieldId: 'ZeOjbxP7naiU0pAAK6q2', name: 'Thể hiện 2 cảm xúc tác động hoặc nhiều hơn (VD: vui, buồn, ngô nghê, sợ, ngạc nhiên). Phản ứng lại không cần đi kèm giao tiếp mắt.  ' },

    // Kỹ năng bắt chước

    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Khi người lớn bắt chước hành động mà trẻ đang thực hiện, trẻ sẽ nhìn người lớn và/hoặc lặp lại hành động đó và quan sát xem người lớn có bắt chước lại lần nữa hay không.  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Khi người lớn thực hiện một hành động trên một vật mà trẻ đã từng thực hiện trước đó, trẻ sẽ bắt chước hành động đó  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Khi người lớn thực hiện một hành động trên một vật mà trẻ chưa từng thực hiện trước đó, trẻ sẽ bắt chước hành động đó.  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Khi người lớn thực hiện hai đến ba hành động khác nhau trên cùng một vật, trẻ sẽ bắt chước hành động đó  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Trẻ bắt chước được 8 hành động trở lên trên vật thể trong vòng 5 giây sau khi người lớn làm theo. Ví dụ như đập hai vật vào nhau, đặt vật vào hộp ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Bắt chước hai động tác khác nhau cho mỗi bài hát và bốn đến năm bài tập khác nhau để thực hiện. Ví dụ bao gồm các cử chỉ trong bài hát (ví dụ: "Five Little Monkeys," "Eensy-Weensy Spider"), các trò chơi vận động (ví dụ: "Motorboat," "Ring around the Rosy"), hoặc các trò chơi khác (ví dụ: Trẻ bắt chước 10 động tác vận động khác nhau trong vòng 5 giây theo mẫu của người lớn. Peekaboo).  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Mô phỏng sáu hành động khác nhau mà trẻ không thể tự mình thực hiện. Ví dụ như đặt tay lên đầu, đặt tay lên tai hoặc vỗ má  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Mô phỏng chuyển động vùng miệng và mặt trong vòng 5 giây so với người lớn. Ví dụ như lè lưỡi, thổi hơi hoặc phồng má  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Gồm 4 – 5 các nguyên âm khác nhau và 4 – 5 phụ âm khác nhau  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Bắt chước ít nhất 5 âm khác nhau  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Bắt chước 10 từ (gần đúng) hoặc hơn  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Có một số hành động quen thuộc; không nhắc  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Thực hiện được gần đúng tối thiểu 5 hành động ở ngay lần làm mẫu đầu tiên  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Việc này bao gồm bắt chước một chuỗi gồm 3 hành động có liên quan hoặc nhiều hơn (VD: mở nắp hộp phân loại hình khối, lấy các hình khối ra, đập nắp lại và sắp xếp các hình khối)  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Trẻ bắt chước một cách nhất quán tối thiểu 4 hành động chơi giả vờ với mô hình theo tự nhiên, với bản thân cũng như với người khác  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Bắt chước 2 chuỗi chuyển động trong bài hát/ trò chơi  ' },
    {fieldId: 'jOdWy1TwAzuEy1lRXT7i', name: 'Trẻ bắt chước một cách đều đặn các cụm hai từ ' },

    // Nhận thức

    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Theo dõi trực quan các vật thể khi chúng di chuyển trong không gian  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Vừa nhìn vật vừa với tay lấy vật  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Khi người lớn di chuyển một vật thể qua lại trước mặt trẻ, trẻ sẽ dõi theo vật thể đó bằng mắt  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Nhận biết và quan sát các vật thể xung quanh ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Có khả năng đưa vật được đặt trong tay lên miệng ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Khi nhìn thấy một vật thể nằm ngoài tầm với, trẻ sẽ cố gắng với tới hoặc di chuyển về phía vật đó  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Chuyển một vật từ tay này sang tay kia  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Khi thao tác với một vật thể, sử dụng hai đến ba hành động khác nhau (ví dụ: đập, đẩy, ném) ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Khi một vật rơi xuống, trẻ theo dõi chuyển động của vật đó bằng ánh nhìn trong suốt quá trình rơi  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Khi một vật bị giấu đi trong lúc trẻ đang quan sát vật đó, trẻ sẽ cố gắng tìm kiếm nó.  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Di chuyển đồ vật vào và ra khỏi các vật chứa (ví dụ: bỏ một quả bóng vào xô rồi lấy ra)  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Trẻ có thể phản ứng với mệnh lệnh bằng lời nói (ví dụ"Đặt ở đây") hoặc tín hiệu bằng cử chỉ (ví  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'dụ: đưa tay cho trẻ) trong vài lần thử đầu tiên, nhưng trẻ cần tự hoàn thành việc ghép/phân loại ít nhất năm đồ vật khác nhau.Ví dụ như ghép/phân loại tàu hỏa và đường ray, bút chì màu và giấy, hoặc que và hình tròn trong các hộp đựng riêng biệt  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Trẻ có thể phản ứng với lời hướng dẫn bằng lời nói (ví dụ: "Đặt ở đây") hoặc tín hiệu bằng cử chỉ (ví dụ: đưa tay cho trẻ) trong vài lần thử đầu tiên, nhưng trẻ cần tự hoàn thành việc ghép/phân loại ít nhất năm bức tranh khác nhau ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Trẻ có thể phản ứng với mệnh lệnh bằng lời nói (ví dụ: "Đặt ở đây") hoặc tín hiệu bằng cử chỉ (ví dụ: đưa tay cho trẻ) trong vài lần thử đầu tiên, nhưng trẻ cần tự hoàn thành việc ghép nối/phân loại ít nhất năm cặp đồ vật/hình ảnh khác nhau  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Trẻ có thể ghép/phân loại năm màu trở lên. Việc này có thể được thực hiện theo hướng dẫn bằng lời nói (ví dụ: "Đặt ở đây") hoặc bằng cử chỉ (ví dụ: đưa tay cho trẻ) trong vài lần thử đầu tiên, nhưng sau đó trẻ cần tự hoàn thành việc ghép/phân loại một cách độc lập. Ví dụ:  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'ghép/phân loại các khối màu đỏ với màu xanh lam, các chốt màu cam với màu xanh lá cây, hoặc các quả bóng màu vàng với màu tím vào các hộp đựng riêng biệt  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Ghép và phân loại ít nhất 5 hình dạng khác nhau  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Trẻ ghép và phân loại ít nhất ba kích cỡ khác nhau của các đồ vật không giống nhau  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Trẻ em ghép và sắp xếp các mẫu  thiết kế và đường nét vẽ  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Trẻ ghép và phân loại các đồ vật không giống nhau dựa theo một danh tính chung (VD: các ô tô, các con ngựa, tất, bóng, giầy, cốc).   ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Trẻ nhóm các đồ vật theo chức năng: ăn, mặc, đồ chơi, vẽ   ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Trẻ nhận biết được khi thiếu một đồ vật trong một bộ và có yêu cầu về đồ vật đó hoặc tìm kiếm nó (VD: một miếng ghép bị thiếu, một chiếc giầy bị mất, một chiếc cốc bị thiếu)   ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Trẻ ghép/ phân loại các đồ vật theo màu sắc và hình dạng, hoặc hình dạng và kích cỡ ….   ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Xác định được số lượng tối thiểu 5 trong mỗi hạng mục. Có thể trong phản ứng lại với tín hiệu bằng lời nói của người lớn (VD: “Số 6 đâu?”, “Chỉ cho cô bút màu xanh?”, hoặc “Chữ cái … đâu?”) hoặc thực hiện một vài lần thử đầu tiên, nhưng trẻ cần tự xác định được ít nhất ở 5 lần thử.  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Xác định được ít nhất 3 đồ vật bị giấu. Người lớn có thể thăm dò bằng cách cho trẻ xem 3 đồ vật (VD: đồng xu, quả bóng nhỏ, que) và sau đó chụp mỗi cái cốc vào từng mục. Người lớn đợi 7 giây và sau đó cho xem bản copy thứ hai của các đồ vật bị giấu đi (VD: quả bóng nhỏ) và hỏi “Quả bóng khác đâu?”. Phản ứng lại có thể là phát âm (“Kia”) và hoặc cử chỉ điệu bộ (VD: chỉ tay/ cầm cốc lên). Giao tiếp mắt là không cần thiết. Người lớn nên cho thử 3 lần hoặc nhiều hơn.  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Hiểu được mối quan hệ cả bằng lời nói (VD: đếm đến 5 đồ vật) hoặc bằng cử chỉ điệu bộ (VD: chạm vào hoặc ghép nhóm 5 đồ vật).  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Xác định được số lượng 5 đối tượng hoặc nhiều hơn. Người lớn có thể cho trẻ đếm những đồ vật yêu thích, chẳng hạn như kẹo, đoàn tàu hoặc các khối gỗ. Người lớn có thể đếm mục đầu tiên để bắt đầu, nhưng trẻ phải tiếp tục và tự kết thúc.  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Có thể trong phản ứng với tín hiệu bằng lời nói của người lớn (VD: “Tiếp theo là gì?”). Trẻ cần tự xâu chuỗi và kể lại khi được hỏi “Kể cho cô về cái đó” đối với 3 chuỗi tranh khác nhau hoặc nhiều hơn.  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Đếm từ 1 đến 20 theo trật tự ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Chạm hoặc chỉ tay vào tranh ảnh hoặc đồ vật trong khi đếm, chạm hoặc chỉ một lần cho mỗi số.  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Cầm số đồ vật đúng cho người lớn khi được yêu cầu.  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Cầm số vật đúng khi người lớn yêu cầu (“ đưa cho con bánh” hoặc “Mẹ có thể được hai cái gối không?”)  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Sử dụng 2 khái niệm hoặc nhiều hơn, gồm “1”, “vài” và “tất cả” trong khi nói  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Sử dụng 2 khái niệm hoặc nhiều hơn, gồm bên cạnh, đằng sau và đằng trước trong khi nói  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Ghép 5 đồ vật hoặc nhiều hơn với các từ gồm 3 – 4 chữ cái được viết ra.  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Đọc và phát âm 10 từ đơn hoặc nhiều hơn về các hành động và đồ vật thông thường.  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Đưa, chỉ tay, cho xem hoặc nói chính tên mình trong nhóm 3 tên khác trong đó có một tên có chữ cái đầu tiên giống với tên của trẻ ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Đề cập đến ý nghĩa của 3 ký hiệu và biểu tượng hoặc nhiều hơn. VD: ký hiệu dừng lại, đèn xanh, biểu tượng “không” nói chung.  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Đề cập đến ý nghĩa của 3 ký hiệu và biểu tượng hoặc nhiều hơn. VD: ký hiệu dừng lại, đèn xanh, biểu tượng “không” nói chung.  ' },
    {fieldId: 'Jr5TN0Q2XH1zOGN9oT1f', name: 'Khi người lớn đề cập đến một khái niệm nào đó, trẻ nói tên khái niệm ngược lại. VD: Người lớn nói “Con chuột nhỏ, nhưng con voi thì ….” và trẻ nói “to”. Hoặc “Con chuột nhỏ, con chim cũng …” và trẻ nói nhỏ  ' },

    // Kỹ năng chơi

    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Với ba đến năm vật thể, trẻ tác động lên chúng bằng cùng một kiểu đơn giản, chẳng hạn như xoa, vỗ hoặc liếm  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Cầm mỗi tay một vật, trẻ sử dụng cùng một sơ đồ thao tác trên cả hai vật, chẳng hạn như đập, lăn hoặc ném  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Sử dụng hai vật thể với nhau bằng cách đập, xếp chồng hoặc các thao tác khác  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Nhận thấy rằng một thao tác tác động lên một đối tượng có thể tạo ra kết quả thú vị (ví dụ: nhấn nút, thổi chong chóng) và lặp lại thao tác đó để xem kết quả một lần nữa  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Khi tương tác với các đối tượng, hệ thống sẽ đặt chúng ở vị trí chính xác  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Khi người lớn làm mẫu hành động đẩy xe hơi hoặc xe lửa, hãy bắt chước hành động đẩy đó bằng chính vật thể đó  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Hành động cần được trẻ tự khởi xướng chứ không phải là phản ứng lại theo mẫu của người lớn. Hành vi phải phù hợp với khả năng tương tác của đồ vật. Ví dụ như lắc lục lạc, gõ búa, lăn hoặc nảy bóng, hoặc xếp khối  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Hoạt động chơi phù hợp với lứa tuổi phát triển (nghĩa là không bị giới hạn hoặc lặp đi lặp lại một cách rập khuôn), có liên quan đến đồ vật/hoạt động đó, và bao gồm các hành động một bước trên đồ vật. Các ví dụ bao gồm: thả các khối hình vào hộp thả hình, thả các quả bóng vào đường ray bóng/tháp bóng, cắm các chốt vào lỗ, hoặc tháo rời các hạt chuỗi xâu vòng  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Trò chơi bao gồm việc hoàn thành độc lập đồ vật/hoạt động. Người chơi có thể chuyền cho người khác năm món đồ chơi trở lên. Ví dụ như đặt vòng lên giá xếp vòng, lấy cốc lồng vào/ra, ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Khi người lớn sử dụng một vật dụng theo cách thông thường (ví dụ: đưa cốc lên miệng, áp điện thoại vào tai, ăn bằng thìa), hãy bắt chước hành động tương tự với vật dụng đó  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Tự nhiên sử dụng đồ vật theo cách có chức năng (ví dụ: đưa cốc lên miệng, áp điện thoại vào tai, ăn bằng thìa).  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Trò chơi liên quan đến đồ vật/hoạt động và bao gồm các hành động một bước với đồ vật. Chuẩn bị 8-10 món đồ chơi cho trẻ nhỏ. Ví dụ như ném bóng, lăn xe hoặc đánh trống.  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Hoạt động chơi bao gồm việc tự hoàn thành một chuỗi đồ vật/hoạt động một cách độc lập. Đạt mục này khi trẻ thực hiện được với 8–10 đồ chơi. Các ví dụ bao gồm: lấy các khối hình ra khỏi hộp/bỏ các khối hình vào hộp, lăn và đập dẹt đất nặn, hoặc gắn các hạt chuỗi xâu vòng (pop beads) lại với nhau rồi tháo rời ra.  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Trò chơi bao gồm việc hoàn thành độc lập đồ vật/hoạt động, có từ sáu đến tám món đồ chơi. Ví dụ như mở/đóng hộp đựng, lấy đồ vật vào/ra, thực hiện các hành động khác nhau với đồ vật ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Các hành động này tuân theo quy tắc xã hội và hướng đến bản thân chính trẻ. Có thể là phản ứng lại với hình mẫu người lớn, nhưng việc sử dụng độc lập, tự phát là cần thiết cho ít nhất một hành động. Ví dụ bao gồm đặt điện thoại vào tai, chải tóc bằng lược/bàn chải, đưa thìa/nĩa lên miệng, lau mũi bằng khăn giấy, đưa cốc lên môi, đeo vòng hạt  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Hoàn thành hoạt động một cách phù hợp và thể hiện một số nỗ lực dọn dẹp (ví dụ: đặt đồ vật vào hộp đựng, đưa đồ dùng cho người lớn). Có thể phản ứng theo hiệu lệnh bằng lời nói hoặc cử chỉ của người lớn để bắt đầu hoạt động thường nhật, nhưng cần tham gia mà không cần sự hỗ trợ về thể chất  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Trẻ thể hiện nhận thức về chức năng liên quan đến bộ trò chơi  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Đạt yêu cầu nếu trẻ tạo được 5 âm thanh hoặc nhiều hơn trong trò chơi  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Trẻ cần tự phát hành động; không đạt nếu chỉ bắt chước  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Trẻ cần tự phát thực hiện liên tiếp tối thiểu 2 hành động có liên quan đến một hoạt động. Không vượt qua nếu chỉ bắt chước.  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Vượt qua nếu trẻ có thử nghiệm và giải quyết vấn đề khi mắc lỗi trong trò chơi có đồ vật  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Người lớn có thể đưa ra một vài bộ xếp hình hoặc các dụng cụ hình ảnh không gian, nhưng trẻ cần chơi một mình bằng cách thực hiện trò chơi phù hợp mà không cần chỉ dẫn bằng lời quá 2 lần, thì cho vượt qua mục này. Vẫn cho qua nếu có một số hành động lặp đi lặp lại trong trò chơi  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Người lớn có thể bày vật liệu ra (đất nặn, các dụng cụ nghệ thuật, sách, đồ để chơi giả vờ), nhưng trẻ cần chơi một mình bằng cách thực hiện các hành động chơi phù hợp không cần quá 2 chỉ dẫn bằng lời thì vượt qua mục này. Vẫn cho qua nếu có một số hành động lặp đi lặp lại trong trò chơi ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Trẻ chơi độc lập gồm lấy dụng cụ, di chuyển đến địa điểm chơi, biết thu dọn và cất dụng cụ khi kết thúc. Việc này có thể bao gồm cả các hoạt động chơi tự do theo hướng mở và có kết thúc  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Xây dựng được 3 đồ hình hoặc nhiều hơn. Các đồ vật có thể là các xe tải đi trên đường, các khối gỗ để xâu dựng, các hạt xâu vòng cổ.  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Các VD: xây dựng đường ray, đẩy tàu hỏa và đâm vào tàu hoặc chia đất nặn, dung dụng cụ cắt theo hình dạng, lấy hình cắt ra  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Các VD: giả vờ rót nước quả và cho em bé ăn, lấy chăn và đặt búp bê vào giường hoặc đặt thú bông trong xe ô tô và đẩy ô tô đi. ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Xếp đặt chỗ trong bối cảnh phù hợp khi chơi. Các VD: Bố ngồi trong ghế bành để xem TV hoặc đặt mẹ vào ô tô để lái đến cửa hàng ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Thực hiện 3 hành động trở lên không cần người lớn nhắc nhở.  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Sắp xếp tối thiểu 2 đồ dùng trong 3 hoặc nhiều hơn các chủ đề chơi khác nhau. Các VD: sắp dĩa và đĩa cho em bé ăn, đội mũ lên đầu mình và đầu người khác để chơi trò mặc trang phục.  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Sử dụng các mô hình để thể hiện 5 hoặc nhiều hơn các hành động trong ít nhất 3 kịch bản chơi. VD: Mẹ lái xe tới cửa hàng, anh trai đuổi bắt chị gái, hoặc con chó nhỏ đang ăn.  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Sử dụng 3 vật thay thế hoặc nhiều hơn. VD: sử dụng một khối gỗ giả làm điện thoại, một ống nhỏ giả làm cái chai, hoặc một hộp nhỏ giả làm ô tô. ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Gọi tên 10 hành động giả vờ hoặc nhiều hơn và/ hoặc giả vờ chơi ít nhất 3 hành động chơi một cách tự phát hoặc phản ứng lại với các câu hỏi. ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'VD: rót nước, trộn thức ăn, đổ thức ăn vào bát, đặt vào trong mũ cứu hỏa, “lái” xe cứu hỏa, và nhảy ra khỏi lửa  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Đưa ra tối thiểu 3 chỉ dẫn phù hợp để đối tác thực hiện trong vài khía cạnh trò chơi, thực hiện qua 2 đến 3 trò chơi  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Chơi 3 sự kiện hoặc nhiều hơn, mỗi sự kiện gồm ít nhất 3 hoạt động được gắn kết vào nhau (xem mục 4 ở trên), tương tác với người khác trong suốt hoạt động với đồ vật và khi nói.  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Chơi theo chủ đề của 3 câu chuyện hoặc nhiều hơn với đối tác bằng cách sử dụng hành động và lời nói như được mô tả trong mục trên, VD: 3 chú lợn con  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Đề cập đến vai trò (VD: “Con làm Mẹ”) và thực hiện các màn chơi cùng lời nói, hoạt động và cử chỉ điệu bộ phù hợp với vai trò, có 3 hoặc nhiều hơn 3 hoán đổi vai với đối tác.  ' },
    {fieldId: 'gxZsB2xYu0IiJel5Ni5z', name: 'Làm theo 5 hoặc nhiều hơn hướng dẫn bằng lời hoặc phi ngôn ngữ của đối tác bằng cách bắt chước hành động của đối tác hoặc phản ứng lại với những chỉ dẫn của đối tác.  ' },

    // Vận động tinh

    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Có thể là phản ứng theo hiệu lệnh của người lớn để bắt đầu thói quen, nhưng trẻ cần tự đặt một đến hai hình khối một cách độc lập  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Có thể là phản ứng theo hiệu lệnh của người lớn để bắt đầu thói quen, nhưng nó có thể tự đặt ba vòng trở lên một cách độc lập  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Có thể là phản ứng theo hiệu lệnh của người lớn để bắt đầu thói quen, nhưng bé tự đặt ba mảnh trở lên một cách độc lập ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Có thể là phản ứng theo hiệu lệnh của người lớn để bắt đầu thói quen, nhưng trẻ cần tự đặt ba hoặc nhiều chốt trở lên  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Có thể là phản ứng theo tín hiệu của người lớn để bắt đầu thói quen, nhưng cần phải tự nhấn các nút một cách độc lập  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Có thể là phản ứng theo hiệu lệnh của người lớn để bắt đầu thói quen, nhưng cần phải tự tháo rời ba hạt hoặc mảnh ghép Duplo trở lên  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Người lớn có thể đặt đồ chơi trong tầm với của trẻ nhưng không được hỗ trợ thêm gì khác  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Có thể là phản ứng theo hiệu lệnh của người lớn để bắt đầu bài tập, nhưng trẻ cần xếp chồng ít nhất ba khối/cốc một cách độc lập  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Hành động này có thể là phản ứng trước tín hiệu của người lớn để bắt đầu thói quen, nhưng trẻ cần phải tự cầm và tạo dấu hiệu một cách độc lập. Các dấu hiệu không cần phải có hình dạng dễ nhận biết  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Có thể là phản ứng theo hiệu lệnh của người lớn để bắt đầu thói quen, nhưng trẻ cần phải tự cầm và đập đồ chơi một cách độc lập  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Có thể là phản ứng theo hiệu lệnh của người lớn để bắt đầu thói quen, nhưng trẻ cần có khả năng  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'cầm nắm đồ vật và tự xúc/cào/rót một cách độc lập  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Có thể là phản ứng theo hiệu lệnh của người lớn để bắt đầu thói quen, nhưng trẻ cần xếp chồng ít nhất ba Lego một cách độc lập  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ hoàn thành đặt hình dạng vào khuôn một cách độc lập; có thể thử và mắc lỗi nhưng không được nhắc hay hỗ trợ  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ tự mình dựng một hình tháp gồm 8 – 10 khối gỗ giữ được thăng bằng  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ sao chép một vài mô hình khối bao gồm tối thiểu 3 khối gỗ(VD: tháp thẳng đứng, đường ngang, cây cầu)  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ sử dụng các dạng đồ vật đan cài vào nhau và lắp ráp số lượng 5 hoặc nhiều hơn theo một số cách khác nhau ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ bắt chước các thao tác chơi với đất nặn  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Người lớn có thể phải giúp bóc một góc để trẻ có thể bóc được miếng dán ra, nhưng trẻ phải tự bóc hẳn miếng dán ra khỏi tờ miếng dán và dán vào tờ giấy một cách độc lập  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Đây không phải là một bài kiểm tra về sức khỏe – nắp nên dễ mở phù hợp với trẻ  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ có thể tự kéo khóa hết xuống; trẻ có thể kéo khóa lên trên cùng, mặc dù người lớn có thể phải giúp chập 2 đường khóa vào nhau cho trẻ.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ xâu tối thiểu 5 hạt, các miếng hình mì ống, các vòng nhẫn … vào một dây to mà không cần trợ giúp hay nhắc nhở.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ bắt chước tối thiểu 3 hình thức hành động khác nhau với các dụng cụ viết  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Không cần là phải cắt rời. Có thể sử dụng kéo của trẻ hoặc của người lớn. Người lớn có thể chỉ cách cầm kéo nhưng trẻ phải tự cắt. Không cần phải cầm kéo một cách hoàn hảo. Cần phải thực hiện được 3 lần cắt.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ tự nhặt được 5 miếng hoặc nhiều hơn trên bàn và đặt từng miếng vào khe, cả theo đường thẳng ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ có thể xâu chuỗi các đồ vật trên nhiều loại dây các nhau  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ tự hoàn thành bảng ghép; có thể thử nghiệm và mắc lỗi nhưng không được nhắc hay hỗ trợ.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ có thể bắt chước một cách nhất quán và tự phát các hành động (có thể được hướng dẫn) bất kể là ở chỗ nào.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ nhảy và di chuyển về địa điểm nào đó, từ một bậc thấp tới một mặt phẳng.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ tự thực hiện bảng ghép với 5-6 miếng khớp hoàn chỉnh  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Bắt chước mỗi hình ở tối thiểu một lần. Người lớn làm mẫu và có thể sử dụng lời nhắc (VD: “Con vẽ đi”).  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Sử dụng 5 khối hoặc nhiều hơn để xây 3 cấu trúc khác nhau hoặc nhiều hơn. Các dụng cụ có thể là khối gỗ, Lego, que có khớp nối nam châm …)  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Xâu qua 3 lỗ hoặc nhiều hơn. Người lớn có thể nhắc bằng lời (VD: “Đặt nó vào đây”) hoặc thực hiện lần thử đầu tiên.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Di/tô theo tối thiểu là 3 – 4 lần đường thẳng và đường cong bằng ngón tay và dụng cụ vẽ. Người lớn có thể làm mẫu lần thử đầu tiên.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Sử dụng tối thiểu 2 công cụ để nhặt và thả 2 hoặc nhiều hơn các đồ vật. Các VD: sử dụng một chiếc thìa to để xúc/ thả một miếng đồ ăn hoặc cái kẹp để kẹp lên/ thả xuống các khối gỗ.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Di/tô theo 3 hình dạng khác nhau hoặc nhiều hơn (VD: hình vuông, hình tròn, hình tam giác, hình chữ nhật). Có thể sử dụng khung nhựa hoặc các đường chấm sẵn trên giấy.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Cắt không cần theo một đường, nhưng phải cắt được tờ giấy ra làm hai. Người lớn có thể thể hiện cách cầm kéo và cắt dọc tờ giấy.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Cắt dọc chính xác theo đường. Người lớn có thể làm mẫu ở lần thử đầu tiên.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Người lớn có thể nhắc bằng lời (VD: Đầu tiên làm cái này, sau đó làm cái này”) hoặc thể hiện các bước trong lần thử đầu tiên. VD: cắt và dán, chấm mực lên giấy, gấp giấy và cắt theo đường gấp ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Thực hiện 3 hình dạng khác nhau hoặc nhiều hơn. Đạt khi sử dụng tối thiểu 2 dụng cụ. Các VD: vo tròn đất nặn, kẹp đất và cắt bằng dao để tạo thành một con rắn, hoặc vo tròn thành dạng quả bóng và giả vờ ăn bằng dĩa.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ tô màu chủ yếu trong khuôn hình, và chọn các màu khác nhau để hoàn thành bức tranh trên giấy ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ sao chép hình tròn, hình vuông, hình tam giác và một số chữ cái có thể nhận dạng được  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ tự vẽ một số hình dạng và chữ cái/ con số có thể nhận dạng được  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ thực hiện cả copy và tự vẽ 4 – 5 hình dạng, 4 – 5 chữ cái và một vài con số có thể nhận dạng được.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ tự nhớ các chữ cái tạo nên tên mình và viết ra được  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ dung bút di theo các đường nét mẫu ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Nhìn chung trẻ tô màu bên trong đường viền  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ có thể di theo các dấu chấm trong chuỗi con số ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ có thể tiếp tục ghép hoặc nối tranh ảnh của đồ vật bằng một đường thẳng (như trong sách hoạt động của bé).  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ copy 5 nét vẽ hoặc nhiều hơn và tự tạo 2 – 3 bức tranh có thể nhận dạng được.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ gập đôi tờ giấy theo mẫu, cho vào trong phong bì  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ cắt các góc và cạnh của các hình dạng lớn (7,5cm hoặc lớn hơn) bằng cách tự sử dụng kéo ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ cắt được các hình dạng đơn giản to nhỏ khoảng 7,5 cm ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Khi người lớn làm mẫu hoạt động, trẻ có thể xâu chuỗi hoạt động và tự hoàn thiện, mỗi bước gồm 1 kỹ năng và trẻ có thể thực hiện được một cách tự tin ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ sử dụng một số dụng cụ nghệ thuật để tạo bức tranh. Trẻ cũng có thể bắt chước mô hình của người lớn bằng cách sử dụng từng dụng cụ này.  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ thường xuyên cầm bút bằng 3 ngón tay đúng cách  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Trẻ thu thập các vật liệu để thiết kế các sản phẩm phức tạp, và cũng có thể copy các thiết kế của người khác, cả mô hình 3D lẫn tranh ảnh hoặc các hình vẽ. ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Xếp hình có nhiều miếng ghép ăn khớp. vượt qua 3- 5 xếp hình khác nhau  ' },
    {fieldId: '7GDprhycm7vmjdbuDiny', name: 'Tự sử dụng tất cả các công cụ ' },

    // Vận động thô

    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Có thể không bám vào người lớn hoặc vật thể (bàn, ghế) để đá bóng. Giữ thăng bằng; không ngã; có thể vụng về  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ có thể vịn vào lan can hoặc tay người lớn, đặt cả hai chân lên mỗi bậc thang. Không được đặt tay hoặc đầu gối lên bậc thang.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Có thể thực hiện mà không cần giúp đỡ. Các VD gồm xe đạp đồ chơi, ngựa cưỡi, ghế lắc dành cho trẻ con hoặc người lớn.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Sử dụng các phản ứng tự bảo vệ hoặc giữ thăng bằng (VD: chống tay xuống, vươn tay ra, bảo vệ đầu).  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Thể hiện nhận thức về cơ thể trong mối tương quan với đồ vật bằng cách bước qua hoặc đi quanh đồ vật.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Có thể thực hiện mà không cần giúp đỡ và có lực ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Người lớn có thể bắt đầu thói quen nhưng trẻ thể hiện sự quan tâm bằng cách lăn bóng về hướng người lớn tối thiểu 2 vòng  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ khởi xướng một cách nhất quán các hành động phù hợp với một số trang thiết bị thấp ở sân chơi ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ tự ngồi lên xe ba bánh đúng chỗ để lái và cố gắng/ thử đạp bàn đạp nhưng có thể cần sự hỗ trợ ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ có thể tự xoay sở với xe kéo hoặc xe cút kít để di chuyển đồ vật trên sân chơi  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ đá quả bóng lớn vào trúng đích ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ đào bằng xẻng, xúc vật liệu lên, và tự chuyển vào thùng/ hộp chứa.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Khi được hướng dẫn nhưng không trợ giúp, trẻ cầm khăn ăn lên và lau một cách phù hợp ở mỗi phần hướng dẫn. Không cần làm suốt mà chỉ cần làm lướt qua một chút  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Khi người lớn cầm hoặc đặt bát hoặc đĩa trước trẻ, trẻ sử dụng dụng cụ ăn để chuyển đồ ăn sang đĩa của nó một cách độc lập. Có thể lúng túng. Người lớn có thể dùng tín hiệu.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Tại bàn, khi một người yêu cầu trẻ chuyển đồ, trẻ nhìn đồ vật đó và cầm lên, sau đó chuyển nó cho người ở bên trái hoặc phải. Trẻ cần phản ứng lại với yêu cầu bằng cách tìm kiếm đồ vật và cố gắng tự cầm nó lên. Nếu ai đó chuyển một hộp đựng cho trẻ và hướng dẫn trẻ chuyển nó cho người kế tiếp, trẻ làm theo chỉ dẫn mà không cần nhắc nhở.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Đạp pê-đan và tự lái theo một đường nhất định, phối hợp tốt  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Đá mà không cần bám vào đồ vật/ người khác. Không vấp ngã. Đá 3 lần hoặc nhiều hơn.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Leo trèo và sử dụng các trò chơi ở mức thấp (VD: đu quay, ván trượt nhỏ, ván bập bênh) và các thiết bị trò chơi ở mức cao (VD: đu dây, cầu khỉ, ván cao). Có thể bám vào rào chắn.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Chơi trong tối thiểu 5 phút  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Bắt chước 5 hành động hoặc nhiều hơn trong tối thiểu 3 bài hát. Các VD: bắt chước chuyển động cơ thể trong bài hát, tự bắt chước và ngay lập tức.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Ném thấp tay tối thiểu 3 lần. Không cần trung đích hoàn hảo. Người lớn có thể làm thử 1 – 2 lần ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Nhảy về phía trước 3 lần hoặc nhiều hơn 8 Nhảy lò cò Nhảy lò cò bằng một chân ở ít nhất một lần. Có thể nhảy trong khi vin vào người khác hoặc vật cố định, không ngã.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Nhảy lò cò bằng một chân ở ít nhất một lần. Có thể nhảy trong khi vin vào người khác hoặc vật cố  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Có thể bắt bóng được 6 lần hoặc nhiều hơn ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Ném bóng cao tay và có định hướng  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Tự chơi được đối với tất cả các dụng cụ phù hợp độ tuổi.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ tư điều chỉnh thân người và đá  đượcquả bóng ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Chơi 5 trò hoặc nhiều hơn với bóng  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ đi xe đạp 3-4 bánh tự tin điều khiển được hướng, tốc độ và phanh  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Bắt chước cả 2 và thể hiện một cách trôi chảy ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Đi bộ thoải mái trong hàng, không quá nhanh và không quá chậm, đúng hàng  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Chơi 5 trò hoặc nhiều hơn – biết luật chơi và tham gia tích cực suốt trò chơi mà không cần nhắc nhở hoặc kèm cặp  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Sử dụng bô nếu cần (mặc dù người lớn có thể nhắc đường tới phòng vệ sinh), tự kéo quần/ đồ lót lên và xuống, xả nước và rửa tay.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Tự đi vệ sinh khi cần (không  cần người lớn nhắc) ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ vặn vòi nước, để tay dưới vòi nước, sử dụng xà phòng, xoa xà phòng vào hai tay, rửa sạch xà phòng, tắt nước và lau khô tay bằng khăn.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trong khi rửa trẻ làm ướt khăn, sử dụng xà phòng (sữa rửa mặt) và lau mặt bằng khăn  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Khi người lớn bảo trẻ chải đầu, trẻ lấy lược và chải. Có thể có những ngoại lệ khó đối với mái tóc dài hoặc xoăn  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Xoa người bằng khăn, sử dụng xà phòng và xoa khắp cơ thể. Tự lau khô; có thể cần nhắc bằng hành động  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Từ khi trẻ vào phòng tắm cho đến khi bàn chải và kem đánh răng được đặt lại vào chỗ thích hợp, trẻ có thể tự thực hiện được tất cả các bước  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Tự cài nút, mặc quần, kéo khóa một cách nhanh chóng  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Khi người lớn nói “xì mũi” trẻ lấy khăn giấy và xì mũi ra. Khi trẻ hắt hơi có lấy tay/khăn che miệng ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Khi đến lề đường cùng một người nào đó, trẻ tự động dừng lại, chờ đợi, nhìn và chờ cho người kia thể hiện là nó có thể qua đường ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ đi bộ không cần cầm tay và đi sát người lớn, kiểm soát được vị trí và duy trì khoảng cách của ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ có thể tự đặt đĩa, cốc, khăn ăn và các đồ dùng khác vào đúng chỗ và ngăn nắp. Người lớn có thể cần đánh dấu nơi cần đặt và cung cấp dụng cụ cho trẻ trên bàn.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ có thể quét mứt/bơ lên bánh mì mà không cần xé bánh mì ra  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ tự động lau chỗ nước đổ trên bàn ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ có thể tự rót chất lỏng từ bình đựng vào cốc nhỏ hơn một cách gọn gàng  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Sau bữa ăn, trẻ tự lau dọn và đặt dụng cụ vào đúng chỗ ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Lấy ra 2 thứ khác nhau từ hộp bỏ ra đĩa, đặt lên bàn. VD: dọn nộm rau, bơ và bánh, kem bơ để quét lên bánh, hỗn hợp ngũ cốc và sữa.  ' },
    {fieldId: 'EvH8IShW7sUs0ojOHrfo', name: 'Trẻ thực hiện một số trong các bước nấu ăn như làm bánh quy, bánh kếp, đánh trứng…. ' },

    // Tập trung chú ý

    {fieldId: 'r34oZoUXxuOq8FBEQkf8', name: 'Ngồi yên/ thoải mái trong tối thiểu là 60 giây trong khi tương tác với người lớn  ' },
    {fieldId: 'r34oZoUXxuOq8FBEQkf8', name: 'Các yêu cầu của người lớn nằm trong khả năng hiện tại của trẻ. Có thể gây ồn ào, nhặng xị nhưng không có hành vi hung hăng.  ' },
    {fieldId: 'r34oZoUXxuOq8FBEQkf8', name: 'Không hung hăng hoặc không có tương tác không phù hợp theo như quan sát trong báo cáo của phụ huynh  ' },

    // Cá nhân xã hội

    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Ngồi tại bàn suốt bữa ăn (VD: không đứng dậy hoặc đi khỏi bàn trong bữa ăn; không cần ngồi trong suốt bữa ăn của gia đình).  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Người lớn dọn đồ ăn ra nhưng không trợ giúp gì khác.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Cầm và đưa cốc lên miệng mà không cần trợ giúp. Có thể đổ một chút khi đang uống.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Cầm và đưa thìa lên miệng mà không cần trợ giúp cho hầu hết các lần đưa vào. Thỉnh thoảng có thể làm rơi thức ăn.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Báo cáo của người chăm sóc là đủ.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Cho phép thức ăn mới ở trong đĩa (bát) và có thể cố ăn (VD: chạm, ngửi hoặc cho vào miệng). Không nhất thiết phải ăn.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Người lớn có thể đặt ống hút vào miệng trẻ nếu trẻ chưa từng được cho dùng ống hút trước đó.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Không cần phải tự cởi cúc hay kéo khóa quần áo, nhưng có thể tự cởi các vật dụng (ví dụ: áo sơ mi, quần, giày, tất) với sự hỗ trợ. Ví dụ như người lớn giúp trẻ kéo tay ra khỏi áo và trẻ kéo áo ra khỏi ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Không cần cài khuy hay kéo khóa quần áo nhưng có thể tự mặc đồ (ví dụ: áo sơ mi, quần, giày, tất) với sự hỗ trợ. Ví dụ như người lớn xắn tay áo và trẻ tự kéo đầu qua áo, người lớn giữ giày và trẻ tự xỏ giày, hoặc người lớn giúp trẻ xỏ quần và trẻ tự kéo quần lên.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Có thể được hướng dẫn nếu cần thiết, nhưng có khả năng đặt tay dưới nước ít nhất 5 giây. Báo cáo của người chăm sóc là đủ.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Có thể hướng dẫn nếu cần thiết, nhưng sử dụng khăn để lau khô cả hai tay. Báo cáo của người chăm sóc là đủ  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Có thể hướng dẫn nếu cần thiết, nhưng sử dụng khăn lau/khăn tắm chà/lau hầu hết các bộ phận cơ thể (ví dụ: mặt, tay, bụng, chân). Báo cáo của người chăm sóc là đủ.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Có thể gây sự ồn ào nhưng người lớn có thể thực hiện thói quen mà không có các vấn đề hành vi hung hăng, tự làm đau bản thân hoặc các hành vi nghiêm trọng. ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'VD: cầm lược hoặc chải vào đầu từng lượt một ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Cho bàn chải vào miệng, nếm thử kem đánh răng. Không cần phải chải răng.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Có thể được nhắc nhở hoặc gợi ý (VD: người lớn cầm quần áo, chỉ vào giỏ) nếu cần thiết, nhưng có thể thả quần áo vào giỏ được.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Có thể được nhắc nhở hoặc gợi ý (VD: người lớn cầm khăn giấy, chỉ vào thùng rác) nếu cần thiết, nhưng có khả năng thả được rác vào thùng rác ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Khi trẻ rời bàn, trẻ làm theo các hướng dẫn của người lớn là mang đi một số đồ vật nào đó tới một địa điểm cụ thể mà không cần nhắc nhở ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Trẻ ngồi trong suốt bữa ăn và ở nguyên không cần nhắc hoặc trợ giúp cho đến khi ăn xong, và người lớn ra tín hiệu là nó có thể đi.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Trẻ tham gia tất cả các bước trong bữa ăn nhanh – chờ đợi, yêu cầu món, mang đi, ngồi, ăn, dọn, và rời khỏi mà không cần nhắc nhở. Trẻ ngồi cho đến khi kết thúc và cho đến tận khi người lớn ăn xong. Trẻ vui vẻ đi bộ cùng người lớn ra cửa. Không cần người lớn phải giữ tay. ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Trẻ phản ứng lại một cách vui vẻ với hướng dẫn nếm hoặc cắn hay uống một món nào đó.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Trẻ tự phát ăn một số quả/ rau, bơ sữa, ngũ cốc, và thịt (ngoại trừ những hạn chế thường xuyên nào đó).  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Trẻ tự phát lấy cốc và lấy nước từ vòi hoặc tủ lạnh mà không cần bất kì một hướng dẫn hoặc trợ giúp nào từ phía người lớn. Khi dùng xong, trẻ vặn vòi lại một cách tự phát.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Khi được hướng dẫn, trẻ cởi áo, quần, quần áo lót, tất và giầy mà không cần trợ giúp của người khác, và đặt tất cả quần áo vào nơi đựng phù hợp. Có thể nhắc bằng lời hoặc dùng cử chỉ điệu bộ 1 hoặc 2 lần, nhưng không nhắc bằng hành động. ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Khi được hướng dẫn, trẻ tự mặc quần, quần lót, áo chui đầu. Người lớn có thể hỗ trợ các loại quần áo có khuy cài, khóa, dây buộc hoặc chỉnh đốn lại trang phục cho ngay ngắn giúp trẻ  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Tự cởi bỏ áo khoác và mũ; có thể được nhắc treo vào đúng chỗ  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Sau khi người lớn đưa khăn ẩm và hướng dẫn “Lau mặt con đi”, trẻ lau toàn bộ mặt mà không cần trợ giúp thêm, sau đó đưa lại hoặc đặt xuống khi xong  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Khi được hướng dẫn xì hoặc lau mũi, trẻ đi tới hộp đựng khăn giấy, lấy giấy, xì hoặc lau mũi, và ném giấy đi mà không cần thêm một lời nhắc nào.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Trẻ thực hiện đều đặn hành động cho mỗi bước rửa tay chứ không chỉ là vặn nước mà không cần sự nhắc nhở nào bằng hành động. Người lớn có thể nhắc một số bước bằng cử chỉ điệu bộ hoặc một phần bằng hành động.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Trẻ không chống cự, khóc hoặc các hành động chống đối khi chải đầu hay cắt tóc. Trẻ tham gia bằng cách trợ giúp lau dầu gội, lau khăn. Có thể sử các dụng cụ thúc đẩy mạnh mẽ trong quá trình thực hiện.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Trẻ chơi một cách vui vẻ, đúng chức năng đối với những đồ chơi khi đi tắm thông thường  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Trẻ phải đặt tất cả đồ chơi khi đi tắm vào hộp chứa phù hợp mà không cần nhắc nhở thêm sau khi đã có hướng dẫn lúc ban đầu.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Trẻ chà bàn chải lên hàm răng dưới và trên, ở trước và ở trong khi được hướng dẫn. Có thể nhắc ở các cấp độ hoặc bằng hành động. ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Khi đến giờ và tắt đèn, trẻ ngủ trên giường của trẻ mà không cần sự hiện diện của người lớn trong phòng. Trẻ hiếm khi ra khỏi giường hoặc đi ra khỏi phòng sau khi đã nằm lên giường.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Trẻ hiểu thói quen trước giờ đi ngủ bằng cách khởi xướng 1 hoặc nhiều hoạt động, và tham gia thực hiện các bước khác nhau theo thói quen mà không cần nhắc nhở hoàn toàn.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Người lớn có thể đặt ra tình huống, nhưng sau khi đặt ra và hướng dẫn, trẻ lấy được khoảng 20 đồ ăn từ bồn và đặt chúng vào khay mà không cần bất kì sự trợ giúp nào từ phía người lớn ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Khi bố hoặc mẹ mở máy sấy và đưa giỏ, trẻ kéo tất cả các thứ trong máy sấy ra và cho vào giỏ mà không cần nhắc nhở thêm. Trẻ có thể cần trợ giúp thêm ở một mục khó nào đó.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Thực hiện với khoảng 1 nhóm 10 đôi tất hoặc hơn trong một giỏ, trẻ để tất theo đôi, gập hoặc xếp chúng lại, sau đó thả vào thùng chứa  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Người lớn có thể cung cấp vật liệu và hướng dẫn, nhưng trẻ phải thực hiện hành động mà không cần trợ giúp thêm. ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Không cần cầm đúng cách  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Cả nhà có thể ăn hết bữa ăn mà trẻ không có hành vi nghiêm trọng nào (VD: ném, đập, bò dưới gầm bàn, chạy đi). Trẻ thỉnh thoảng gây ồn ào một chút nhưng có thể được thu hút vào các hoạt động khác (VD: vẽ trên bàn, chơi với các đồ chơi nhỏ)  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Tìm sách biểu tượng/ tranh ảnh, chọn biểu tượng phù hợp và lựa chọn hoặc hoạt động mà không cần trợ giúp. Tự sử dụng tối thiểu 80% thời gian ở nhà và ở trường. Nếu nhà trường không yêu cầu vấn đề này, bỏ qua.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Tự mang tối thiểu một đồ vật. Các VD: ba lô, hộp đồ ăn, áo khoác …  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Cho vào/ lấy ra tối thiểu 3 đồ vật theo yêu cầu. Các VD: hộp đồ ăn, cặp hồ sơ, đồ chơi …  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Tự kéo khóa và đóng cúc không cần nhanh  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Có thể yêu cầu trợ giúp rửa tay nếu không thể với tới bồn  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Kéo quần lên/ xuống. Người lớn có thể cầm đồ cho trẻ để thực hiện bước, nhưng trẻ phải trẻ phải tự kéo lên/ xuống.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Mở/ đóng vòi, sử dụng xà phòng, xoa tay và lau khô. Có thể được nhắc ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Để khăn lên mặt và lau. Có thể được nhắc. ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Có thể nhắc nhở ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Che miệng bằng tay hoặc bằng giấy ăn. Có thể được nhắc  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Người lớn có thể cung cấp khăn, xà phòng và để cho xà phòng vào khăn, nhưng trẻ tự tắm rửa và lau khô các bộ phận cơ thể (VD: mặt, bụng, cánh tay, chân).  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Chải lên/ xuống tối thiểu 5 lần. Người lớn có thể bôi kem vào bàn chải. Có thể nhắc trẻ cầm bàn chải.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Cho đồ ăn/ nước uống vào bát và đem cho vật nuôi, Người lớn có thể hỗ trợ (VD: mở bình, đo lường) hoặc nhắc nhở.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Lấy đi ít nhất 2 đồ hoặc nhiều hơn (VD: đĩa, cốc, bát …) để vào bồn rửa. Có thể được nhắc.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Lấy đi 5 đồ vật hoặc nhiều hơn. Người lớn có thể chỉ chỗ cất vật. Mang ít nhất 2 đồ vật hoặc nhiều hơn (VD: đĩa, cốc, bát …) để vào chỗ đựng. Có thể được nhắc.  ' },
    {fieldId: 'XV4FJbN7cv4UXpN2tOqR', name: 'Cầm các vật dụng cá nhân lên (VD: quần áo, đồ chơi, giầy …) và cất ở nơi phù hợp khi được yêu cầu. Có thể được nhắc. ' },
]